"""Commande /help."""
from __future__ import annotations

from uexinfo.cli.commands import register
from uexinfo.display.formatter import console, section
from uexinfo.display import colors as C

_COMMANDS = {
    "help":    "Aide générale ou /help <commande>",
    "config":  "Configuration : vaisseaux, préférences, trade, scan",
    "ship":    "Raccourci /config ship — gérer les vaisseaux configurés",
    "go":      "Définir la position courante ou destination",
    "lieu":    "Alias de /go",
    "select":  "Filtres actifs (système, planète, station, terminal…)",
    "player":  "Gérer le joueur : vaisseau, position, destination",
    "scan":    "Scanner un terminal (OCR screenshot ou log SC-Datarunner)",
    "auto":    "Contrôle des automatisations (log, signalement, validation)",
    "undo":    "Annuler le dernier scan",
    "trade":   "Prix d'achat/vente, bilan route, routes sc-trade.tools",
    "route":   "Calcul de routes commerciales rentables",
    "plan":    "Plan de vol multi-étapes",
    "info":    "Détail d'un terminal ou d'une commodité",
    "explore": "Navigation hiérarchique : systèmes, vaisseaux, commodités",
    "nav":     "Réseau de transport : nœuds, routes QT, jump points, itinéraires",
    "mission": "Catalogue de missions (scan screenshots, add, edit, list, remove)",
    "dev":     "Mode développeur : import batch screenshots, stats DB, bypass watcher",
    "debug":   "Niveau de trace interne (0 = off, 5 = max)",
    "voyage":  "Planification de voyages — groupe de missions à accomplir",
    "refresh": "Rafraîchir le cache (prix, données statiques)",
    "dest":    "Définir ou effacer la destination  (/dest clear pour effacer)",
    "=":       "Calculatrice  (/calc — ex: = 16x6  = 100/3  = (12+8)*5)",
    "note":    "Notes personnelles par lieu",
    "exit":    "Quitter l'application  (/quit et /bye aussi)",
}

_DETAILS = {
    "player": (
        "/player info                      État joueur (vaisseau, position, dest)\n"
        "/player ship add <nom> [scu]      Ajouter un vaisseau\n"
        "/player ship set <nom>            Vaisseau actif\n"
        "/player ship scu <nom> <n>        Capacité cargo en SCU\n"
        "/player ship remove <nom>         Supprimer un vaisseau\n"
        "/player @<lieu>                   Définir la position courante\n"
        "/player dest @<lieu>              Définir la destination\n\n"
        "@<lieu>  Ex: @gaslight   @stanton.hurston.lorville\n"
        "         Tab après @ pour compléter."
    ),
    "scan": (
        "/scan                        Dernier screenshot Star Citizen (OCR)\n"
        "/scan ecran                  Capture la fenêtre SC en direct (ou presse-papiers)\n"
        "/scan screen                 Alias de /scan ecran\n"
        "/scan screenshot <fichier>   Scanner un fichier image directement\n"
        "/scan log                    Lire TOUS les scans du log SC-Datarunner (défaut)\n"
        "/scan log new                Lire uniquement les nouveaux scans (incrémental)\n"
        "/scan log reset              Remettre l'offset à 0\n"
        "/scan status                 Afficher le dernier résultat\n"
        "/scan history [n]            Historique des n derniers scans (défaut 5)\n\n"
        "Lecture automatique du log :\n"
        "  Si sc_log_path est défini et SC-Datarunner est actif, le log est surveillé\n"
        "  en permanence.  Avant chaque /info, les nouvelles entrées sont lues\n"
        "  silencieusement.  Après les autres commandes, les nouveaux scans sont\n"
        "  affichés automatiquement.  Contrôler avec : auto log on|off\n\n"
        "Nouveaux screenshots :\n"
        "  Si sc_screenshots_dir est défini, les nouveaux fichiers SC sont signalés\n"
        "  après chaque commande.  Contrôler avec : auto signal.scan on|off\n\n"
        "Priorité /scan ecran : fenêtre SC → presse-papiers → dernier screenshot\n\n"
        "Les prix issus d'un scan joueur sont fiables (non en italique) et\n"
        "restent prioritaires sur UEX tant qu'aucune mise à jour plus récente n'existe."
    ),
    "auto": (
        "auto                         Afficher l'état des automatisations\n"
        "auto log on|off              Activer/désactiver la lecture auto du log\n"
        "auto signal.scan on|off      Activer/désactiver le signalement des nouveaux scans\n"
        "auto log.accept on|off       Activer/désactiver la validation auto des valeurs log\n\n"
        "Fonctionnement :\n"
        "  auto log on       → le log SC-Datarunner est surveillé (mtime).\n"
        "                      Avant /info : mise à jour silencieuse de ctx.last_scan.\n"
        "                      Après les autres commandes : affichage des nouveaux scans.\n"
        "  auto signal.scan  → signale aussi les nouveaux screenshots SC détectés.\n"
        "  auto log.accept   → si off, les scans sont affichés mais non stockés en\n"
        "                      historique (confirmation manuelle requise).\n\n"
        "Note : Le / est optionnel — 'auto log on' fonctionne sans /."
    ),
    "undo": (
        "undo                         Annuler le dernier scan (log, screenshot ou OCR)\n\n"
        "Supprime le scan de l'historique et remet ctx.last_scan au scan précédent.\n"
        "Utile si SC-Datarunner a capturé une erreur ou une mauvaise valeur."
    ),
    "note": (
        "/note                               Lister toutes les notes (par lieu)\n"
        "/note -l <lieu>                     Lister les notes d'un lieu\n"
        "/note <message>                     Ajouter une note au lieu courant\n"
        "/note -l <lieu> <message>           Ajouter une note à un lieu précis\n"
        "/note -e                            Formulaire de création (lieu courant)\n"
        "/note -e -n <id>                    Formulaire d'édition de la note <id>\n"
        "/note -r <id>                       Supprimer la note numéro <id>\n"
        "/note -r <lieu>                     Supprimer toutes les notes d'un lieu\n\n"
        "Options :\n"
        "  -l / --lieu <lieu>    Lieu de la note (défaut : position joueur)\n"
        "  -r / --rm <id|lieu>   Supprimer\n"
        "  -n / --num <id>       Numéro de note (avec --edit pour modifier)\n"
        "  -e / --edit           Ouvrir le formulaire d'édition\n\n"
        "Les options précèdent toujours le message.\n"
        "Exemples :\n"
        "  /note j'ai laisse 32 SCU de cuivre sur place\n"
        "  /note -l ARC-L4 medical sature - revenir dans 2h\n"
        "  /note -r 5\n"
        "  /note -e -n 3\n\n"
        "Affichage dans /info : activer/désactiver avec /config info note true|false"
    ),
    "ship": (
        "/ship list                              Lister les vaisseaux configurés\n"
        "/ship add <nom>[, <nom2>, …]            Ajouter un ou plusieurs vaisseaux\n"
        "/ship remove <nom>                      Retirer un vaisseau\n"
        "/ship set <nom>                         Définir le vaisseau actif\n"
        "/ship cargo <nom>                       Afficher les grilles cargo du vaisseau\n"
        "/ship cargo <nom> <32xN> [16xN] …      Définir les grilles (particulier : votre exemplaire)\n"
        "/ship cargo <nom> --all <32xN> [16xN] … Définir les grilles (général : tous les exemplaires du modèle)\n"
        "/ship cargo <nom> --all                 Afficher la config générale du modèle\n"
        "/ship cargo <nom> --clear               Effacer l'override général du modèle\n\n"
        "  Particulier  (sans --all) → stocké dans votre flotte, s'applique à votre vaisseau.\n"
        "  Général      (--all / -a) → stocké dans cargo_grids_ext.json, s'applique à tout\n"
        "               joueur n'ayant pas d'override particulier.\n\n"
        "Alias direct de /config ship — Tab pour compléter les noms de vaisseaux.\n"
        "Exemples :\n"
        "  /ship add Drake_Cutlass_Black\n"
        "  /ship set Drake_Cutlass_Black\n"
        "  /ship cargo Cutlass_Black                       (affiche config actuelle)\n"
        "  /ship cargo Cutlass_Black 16x2 2x6              (grilles perso)\n"
        "  /ship cargo C2_Hercules --all 32x20 2x28        (grilles modèle général)\n"
        "  /ship cargo Cutlass_Black --clear               (retire override modèle)\n"
        "  /ship list"
    ),
    "config": (
        "/config                               Afficher la configuration\n"
        "/config ship add <nom>[, <nom2>, …]   Ajouter un ou plusieurs vaisseaux\n"
        "/config ship remove <nom>             Retirer un vaisseau\n"
        "/config ship set <nom>                Définir le vaisseau actif\n"
        "/config ship cargo <nom> \\[32xN …]     Grilles cargo perso (votre exemplaire)\n"
        "/config ship cargo <nom> --all \\[32xN …] Grilles cargo modèle (général)\n"
        "/config trade profit <aUEC>           Profit minimum par SCU\n"
        "/config trade margin <pct>            Marge minimale en %\n"
        "/config trade illegal on|off          Autoriser les commodités illégales\n"
        "/config cache ttl <secondes>          TTL du cache statique\n"
        "/config cache clear                   Vider le cache\n"
        "/config scan mode ocr|log|confirm     Mode de scan\n"
        "/config scan tesseract <path>         Chemin tesseract.exe\n"
        "/config scan logpath <path>           Chemin app.log SC-Datarunner\n"
        "/config scan screenshots <path>       Dossier screenshots SC\n"
        "/config scan auto_ocr on|off          OCR automatique dès détection (défaut : on)\n"
        "/config scan hour <n>                 Fenêtre /mission scan en heures (défaut : 2)\n"
        "/config scan session_gap <min>        Gap entre sessions en minutes (défaut : 60)\n"
        "/config close normal|dblclick         Comportement du bouton ✕ de l'overlay\n"
        "/config clock on|off                  Horloge en fond de l'overlay (défaut : on)\n"
        "/config cmdhistory <n>                Nombre de commandes+résultats conservés (1-50, défaut : 5)\n"
        "/config player                        Afficher la config joueur\n\n"
        "/config version                       Afficher les versions connues\n"
        "/config version <X.Y>                 Changer la version active (scans anciens ignorés)\n"
        "/config version <X.Y> --reset         Changer + invalider le cache UEX\n"
        "/config version ptu <X.Y>             Enregistrer la version PTU\n"
        "/config version use live|ptu          Basculer d'environnement\n\n"
        "/config uex key <clé>                 Clé secrète personnelle UEX Corp\n"
        "/config sctrade on|off                Activer/désactiver sc-trade.tools\n"
        "/config hotkey <combo>                Hotkey overlay (ex: alt+shift+u)\n"
        "/config magasins on|off               Afficher les magasins dans la vue terminal\n"
        "/config restaurants on|off            Afficher les restaurants dans la vue terminal\n"
        "/config services on|off               Afficher les services dans la vue terminal\n"
        "/config info note on|off              Notes personnelles dans la vue terminal\n\n"
        "Clés en notation pointée (/config <clé> <valeur>) :\n"
        "/config scan.autopos on|off           Auto-position depuis tout scan OCR/log\n"
        "/config scan.log.autopos on|off|quick Auto-position depuis le log SC-Datarunner\n"
        "/config gamelog.enabled on|off        Lire Game.log (le jeu) en direct pour la zone\n"
        "/config gamelog.install_path_live <chemin>  Dossier d'install SC LIVE (contient Game.log)\n"
        "/config gamelog.install_path_ptu <chemin>   Dossier d'install SC PTU (optionnel)\n"
        "/config voyage.calc.nbsaut <n>        Nb max de missions par proposition\n"
        "/config voyage.calc.prop <n>          Nb de propositions (1=critère, ≥2=dist+benef+roi)\n"
        "/config voyage.calc.gap_max <n>       Transit ⚠ au-delà de N Gm\n"
        "/config voyage.calc.favoris <lieux…>  Lieux à privilégier\n"
        "/config voyage.calc.exclure <lieux…>  Lieux à exclure systématiquement\n\n"
        "[dim]scan logpath/mode log lisent app.log de SC-Datarunner (l'outil OCR externe) — gamelog[/dim]\n"
        "[dim]lit Game.log, le fichier écrit par Star Citizen lui-même. Deux fichiers distincts.[/dim]\n\n"
        "/help config close      → détail du comportement de fermeture\n"
        "/help config scan       → détail des options scan OCR\n"
        "/help config clock      → détail de l'horloge de fond\n"
        "/help config cmdhistory → détail de l'historique\n"
        "/help config version    → détail de la gestion des versions"
    ),
    "config version": (
        "Gestion des versions Star Citizen (live et PTU).\n\n"
        "  /config version\n"
        "    Affiche les versions connues (live + PTU) et l'environnement actif.\n\n"
        "  /config version <X.Y>\n"
        "    Change la version de l'environnement actif.\n"
        "    Les scans enregistrés sous une version différente sont ignorés\n"
        "    (conservés mais invisibles). Le cache UEX n'est pas rechargé.\n\n"
        "  /config version <X.Y> --reset\n"
        "    Comme ci-dessus + invalide le cache statique UEX (terminaux,\n"
        "    commodités, systèmes). Les données seront rechargées depuis\n"
        "    uexcorp.space au prochain accès.\n\n"
        "  /config version ptu <X.Y>\n"
        "    Enregistre la version PTU sans changer l'environnement actif.\n\n"
        "  /config version use live|ptu\n"
        "    Bascule l'environnement actif (live ↔ PTU).\n"
        "    Les scans et prix affichés seront ceux de l'environnement choisi.\n\n"
        "  Détection automatique :\n"
        "    Lors du premier accès aux prix UEX, la version du jeu est lue\n"
        "    depuis l'API et enregistrée automatiquement si la config est vide.\n"
        "    En cas de changement de version détecté, une bannière s'affiche\n"
        "    avec les commandes à utiliser.\n\n"
        "  Exemples :\n"
        "    /config version 4.0\n"
        "    /config version 4.0 --reset\n"
        "    /config version ptu 4.0.1-ptu.9660843\n"
        "    /config version use ptu"
    ),
    "config cmdhistory": (
        "/config cmdhistory <n>\n\n"
        "  Nombre de blocs commande+résultat conservés dans la zone de sortie\n"
        "  de l'overlay. Valeur entre 1 et 50, défaut : 5.\n\n"
        "  Chaque commande exécutée ajoute un bloc (ligne de saisie + résultat).\n"
        "  Quand la limite est atteinte, le bloc le plus ancien est supprimé.\n\n"
        "  Exemples :\n"
        "    /config cmdhistory 3    Garder les 3 dernières commandes\n"
        "    /config cmdhistory 10   Garder les 10 dernières commandes\n"
        "    /config cmdhistory      Afficher la valeur actuelle\n\n"
        "  Le changement est sauvegardé mais actif au prochain démarrage."
    ),
    "config scan": (
        "Options de scan OCR et détection automatique de screenshots.\n\n"
        "  /config scan mode ocr|log|confirm\n"
        "    Mode de lecture des terminaux :\n"
        "      ocr     — Tesseract sur le dernier screenshot\n"
        "      log     — Lecture du log SC-Datarunner (défaut)\n"
        "      confirm — Log + confirmation avant enregistrement\n\n"
        "  /config scan auto_ocr on|off\n"
        "    Active/désactive l'OCR automatique des nouveaux screenshots.\n"
        "    Quand activé : dès qu'un screenshot est détecté, il est analysé\n"
        "    en arrière-plan et ajouté à la base (~/.uexinfo/screenshot_db.json).\n"
        "    Le badge '📷 N missions' dans la barre de statut s'allume quand\n"
        "    des missions sont disponibles. Cliquer dessus → /mission scan.\n\n"
        "  /config scan hour <n>           (défaut : 2)\n"
        "    Fenêtre temporelle pour /mission scan : n heures en arrière.\n"
        "    Les missions SC s'oublient à chaque changement de serveur,\n"
        "    donc 2h couvre généralement une session de jeu.\n\n"
        "  /config scan session_gap <minutes>   (défaut : 60)\n"
        "    Gap en minutes entre deux screenshots pour considérer qu'il\n"
        "    s'agit d'une nouvelle session. Utilisé pour regrouper visuellement\n"
        "    les captures dans /mission scan.\n\n"
        "  /config scan tesseract <path>   Chemin vers tesseract.exe\n"
        "  /config scan logpath <path>     Chemin vers app.log SC-Datarunner\n"
        "  /config scan screenshots <path> Dossier des screenshots SC\n\n"
        "  Exemple workflow complet :\n"
        "    1. Ouvrir le menu Contrats dans SC\n"
        "    2. Prendre des screenshots (F12) de chaque mission disponible\n"
        "    3. Le badge 📷 s'allume dans l'overlay → cliquer\n"
        "    4. Sélectionner les missions → Ajouter au catalogue ou au voyage"
    ),
    "config clock": (
        "/config clock on|off\n\n"
        "  Affiche ou masque l'horloge temps réel en fond de la fenêtre overlay.\n\n"
        "  L'horloge affiche l'heure locale (HH:MM:SS) en grands caractères cyan,\n"
        "  très transparents, en bas à droite de la fenêtre.\n"
        "  Elle n'intercepte pas les clics et n'interfère pas avec le contenu.\n\n"
        "  on    (défaut) — horloge visible\n"
        "  off            — horloge masquée\n\n"
        "  Le changement est immédiat (pas besoin de relancer l'overlay).\n"
        "  Le réglage est sauvegardé dans ~/.uexinfo/config.toml.\n\n"
        "  Exemples :\n"
        "    /config clock off   Masquer l'horloge\n"
        "    /config clock on    Réafficher l'horloge\n"
        "    /config             Voir l'état actuel (ligne overlay.clock)"
    ),
    "config close": (
        "/config close normal|dblclick\n\n"
        "  Contrôle le comportement du bouton ✕ de la fenêtre overlay.\n\n"
        "  normal    (défaut)\n"
        "    Un clic sur ✕ ferme définitivement l'overlay.\n"
        "    Équivalent à taper /quit.\n\n"
        "  dblclick\n"
        "    Un clic sur ✕ masque la fenêtre (comme la hotkey alt+shift+u).\n"
        "    Un double-clic sur ✕ ferme définitivement.\n"
        "    Utile quand on bascule souvent entre Star Citizen et l'overlay.\n\n"
        "  Note : le mode bouton ✕ OS (frameless=false) fonctionne de la même\n"
        "  façon : 1er clic sur la croix native → masquer ; 2e clic < 500ms → fermer.\n\n"
        "  Exemples :\n"
        "    /config close dblclick    Activer le mode double-clic\n"
        "    /config close normal      Revenir au comportement classique\n\n"
        "  Le changement est effectif au prochain lancement de l'overlay."
    ),
    "explore": (
        "/explore                         Liste des catégories navigables\n"
        "/explore <système>               Planètes et corps dans le système\n"
        "/explore <sys>.<corps>           Lieux (stations, villes…)\n"
        "/explore <sys>.<corps>.<lieu>    Terminaux et infos du lieu\n"
        "/explore ship                    Fabricants de vaisseaux\n"
        "/explore ship.<fabricant>        Vaisseaux d'un fabricant\n"
        "/explore commodity               Catégories de commodités\n"
        "/explore commodity.<catégorie>   Commodités de la catégorie\n\n"
        "Navigation par point, Tab complétion à chaque niveau.\n"
        "Exemples :\n"
        "  /explore stanton\n"
        "  /explore stanton.hurston.lorville\n"
        "  /explore pyro.bloom\n"
        "  /explore ship.anvil\n"
        "  /explore commodity.metal"
    ),
    "info": (
        "/info <nom>                  Recherche libre (terminal, commodité, vaisseau)\n"
        "/info terminal <nom>         Détail d'un terminal (lieu, système…)\n"
        "/info commodity <nom>        Détail d'une commodité (prix UEX, flags…)\n"
        "/info ship <nom>             Fiche vaisseau (achat, location, cargo)\n"
        "/info list [filtre]          Liste des commodités (tri alphabétique)\n"
        "/info list -p+ [filtre]      Tri par prix croissant\n"
        "/info list -p- [filtre]      Tri par prix décroissant (-p = -p-)\n"
        "/info list -b+ [filtre]      Tri par bénéfice croissant\n"
        "/info list -b- [filtre]      Tri par bénéfice décroissant (-b = -b-)\n\n"
        "Cache de prix :\n"
        "  /info reset-list <terminal>          Efface + recharge la liste depuis UEX Corp\n"
        "  /info reset-price <terminal>         Efface + recharge les prix depuis UEX Corp\n"
        "  /info reset-scan <terminal>          Supprime TOUTES les données scan joueur\n"
        "  /info reset-scan <terminal> <comm>   Supprime le scan d'une commodité précise\n\n"
        "Filtres système (commodités) :\n"
        "  /info --all <commodité>          Tous les systèmes\n"
        "  /info --Nyx,Pyro <commodité>     Filtrer sur Nyx et Pyro\n"
        "  /info --Cur,Nyx <commodité>      Système courant + Nyx\n\n"
        "Exemples :\n"
        "  /info GrimHEX\n"
        "  /info Laranite\n"
        "  /info --all Copper\n"
        "  /info list gold             Commodités contenant 'gold'\n"
        "  /info list -p               Toutes, triées par prix\n"
        "  /info ship Cutlass Black\n"
        "  /info terminal Area 18"
    ),
    "go": (
        "/go                    Afficher position et destination\n"
        "/go <lieu>             Définir la position courante\n"
        "/go from <lieu>        Définir le point de départ\n"
        "/go to <lieu>          Définir la destination\n"
        "/go clear              Réinitialiser\n\n"
        "<lieu> = nom de terminal, station, ville, planète, système"
    ),
    "select": (
        "/select                          Afficher les filtres actifs\n"
        "/select <type> <nom>             Raccourci ajout de filtre\n"
        "/select add <type> <nom>         Ajouter un filtre\n"
        "/select remove <type> <nom>      Retirer un filtre\n"
        "/select clear [type]             Supprimer les filtres\n\n"
        "Types : system | planet | station | terminal | city | outpost"
    ),
    "refresh": (
        "/refresh               Rafraîchir les prix (si TTL expiré)\n"
        "/refresh all           Forcer le refresh complet\n"
        "/refresh static        Données statiques uniquement\n"
        "/refresh prices        Prix uniquement\n"
        "/refresh sctrade       Données sc-trade.tools\n"
        "/refresh status        État du cache (âge, nombre d'entrées)"
    ),
    "trade": (
        "/trade <commodité>              Prix d'achat + vente (résumé)\n"
        "/trade buy <commodité>          Où acheter (terminaux, prix croissant)\n"
        "/trade sell <commodité>         Où vendre (terminaux, prix décroissant)\n"
        "/trade                          Bilan route joueur (position → destination)\n"
        "/trade from <terminal>          Bilan au départ d'un terminal\n"
        "/trade to <terminal>            Bilan vers un terminal destination\n"
        "/trade from <A> to <B>          Bilan explicite A → B\n"
        "/trade sctrade                  Routes optimisées sc-trade.tools\n"
        "/trade best                     Meilleures routes globales (Phase 3 — à venir)\n"
        "/trade compare <commodité>      Comparer UEX et sc-trade.tools (Phase 3)\n\n"
        "Alias : /t\n"
        "/help trade buy      → recherche d'achat\n"
        "/help trade sell     → recherche de vente\n"
        "/help trade bilan    → bilan de route\n"
        "/help trade sctrade  → routes sc-trade.tools"
    ),
    "trade buy": (
        "/trade buy <commodité>\n\n"
        "  Liste les terminaux où acheter la commodité, triés par prix croissant\n"
        "  (le moins cher en tête). Priorité aux terminaux du système courant.\n\n"
        "  Colonnes :\n"
        "    Terminal   Nom du terminal (préfixé 'Système.' si hors système courant)\n"
        "    A/□        Prix d'achat par SCU\n"
        "    Âge        Ancienneté des données UEX Corp\n"
        "    Cargo      Taille de containers disponibles à ce terminal\n\n"
        "  Couleur du terminal selon le statut de stock :\n"
        "    vert = abondant/haut   orange = bas   rouge = rupture\n\n"
        "  Exemples :\n"
        "    /trade buy Copper\n"
        "    /trade buy laranite\n"
        "    /t buy gold\n\n"
        "  Combine avec sell pour voir la marge :\n"
        "    /trade Copper  →  buy + sell en une commande"
    ),
    "trade sell": (
        "/trade sell <commodité>\n\n"
        "  Liste les terminaux qui achètent la commodité (où vendre), triés par\n"
        "  prix décroissant (le plus payé en tête). Priorité au système courant.\n\n"
        "  Colonnes :\n"
        "    Terminal   Nom du terminal\n"
        "    V/□        Prix de vente par SCU (ce que le terminal paie)\n"
        "    Âge        Ancienneté des données\n"
        "    Stock      Niveau actuel/max au terminal (observations joueur ou UEX)\n\n"
        "  Couleur du terminal selon le statut de demande :\n"
        "    vert = demande forte   orange = faible   rouge = saturé\n\n"
        "  Exemples :\n"
        "    /trade sell Copper\n"
        "    /trade sell Medical_Supplies\n"
        "    /t sell gold\n\n"
        "  Combine avec buy pour voir la marge :\n"
        "    /trade Copper  →  buy + sell en une commande"
    ),
    "trade bilan": (
        "/trade                        Bilan route (position → destination courante)\n"
        "/trade from <terminal>        Bilan au départ de ce terminal\n"
        "/trade to <terminal>          Bilan vers ce terminal destination\n"
        "/trade from <A> to <B>        Bilan explicite entre deux terminaux\n\n"
        "  Prérequis :\n"
        "    Position joueur définie  :  @<lieu>  ou  /go <lieu>\n"
        "    Destination définie      :  /dest <lieu>  ou  /go to <lieu>\n"
        "    Vaisseau et cargo        :  /ship set <nom>  (voir /ship)\n\n"
        "  Pour chaque commodité échangeable sur la route :\n"
        "    A/□     Prix d'achat à l'origine\n"
        "    V/□     Prix de vente à destination\n"
        "    Âge     Ancienneté des données UEX\n"
        "    Stock   Niveau de stock achat → vente (○●●○ → ●●●○)\n"
        "    SCU     Quantité estimée chargeable (selon stock et cargo)\n"
        "    Gain    Profit brut estimé  (qty × (V - A))\n"
        "    ROI     Retour sur investissement (%)\n"
        "    ⚠       Risque  (saturation destination + ancienneté données)\n"
        "    Cargo   Packing containers suggéré  ex: [ 8×32□  2×16□ ]\n\n"
        "  Tri par ROI décroissant.\n\n"
        "  Exemples :\n"
        "    /trade                                  Route position → dest\n"
        "    /trade from Port_Tressler               Depuis Port Tressler\n"
        "    /trade to Area18                        Vers Area 18\n"
        "    /trade from Port_Tressler to Area18     Route explicite"
    ),
    "trade sctrade": (
        "/trade sctrade                          Routes sc-trade.tools (auto depuis joueur)\n"
        "/trade sctrade --from <lieu>            Origine manuelle  (alias -f)\n"
        "/trade sctrade --to <lieu>              Filtrer les ventes vers ce lieu  (alias -t)\n"
        "/trade sctrade --ship <vaisseau>        Vaisseau  (alias -s)\n"
        "/trade sctrade --budget <N>             Budget aUEC  ex: 500k, 2000000  (alias -b)\n"
        "/trade sctrade --same-system / --ss     Restreindre au système courant\n"
        "/trade sctrade --margin <N>             Marge minimale %  (défaut 2)  (alias -m)\n\n"
        "  Listings publics sc-trade.tools · aucun compte requis · cache 15 min.\n"
        "  Données affichées en orange (source communauté).\n\n"
        "  --from et --to sont des filtres réels sur les lieux d'achat et de vente.\n"
        "  Si le lieu est introuvable dans sc-trade.tools, un diagnostic est affiché.\n\n"
        "  Auto-remplissage depuis l'état joueur :\n"
        "    origin ← position joueur   dest ← destination   ship ← vaisseau actif\n"
        "    budget ← cargo × 1 000 aUEC  (minimum 10 000)\n\n"
        "  Colonnes :\n"
        "    # · Achat · Commodité · Prix/□ · Vente · Prix/□ · Profit · ROI\n\n"
        "  Exemples :\n"
        "    /trade sctrade\n"
        "    /trade sctrade --same-system\n"
        "    /trade sctrade --budget 500k --margin 3\n"
        "    /trade sctrade --from Port_Tressler --to Area18\n"
        "    /trade sctrade --margin 1"
    ),
    "nav": (
        "/nav                             Stats du réseau (nœuds, routes, jump points)\n"
        "/nav info                        Idem — même chose que /nav seul\n"
        "/nav nodes [système]             Lister les nœuds (filtrable par système)\n"
        "/nav edges [lieu]                Lister les routes (filtrable par nœud)\n"
        "/nav jumps                       Lister les jump points inter-systèmes\n"
        "/nav route <de> <vers>           Calculer le plus court chemin QT\n"
        "/nav add-route <de> <vers> <Gm> [type]   Ajouter une route manuellement\n"
        "/nav add-jump <nom> <sys1> <sys2> <entrée> <sortie> [S|M|L]\n"
        "                                 Ajouter un jump point\n"
        "/nav remove-route <de> <vers>    Supprimer une route\n"
        "/nav remove-jump <nom>           Supprimer un jump point\n"
        "/nav save                        Sauvegarder les modifications\n"
        "/nav raz                         Réinitialiser depuis le fichier source\n\n"
        "Types de route : quantum (défaut) | ground | landing | jump\n\n"
        "Exemples :\n"
        "  /nav route GrimHEX Area18\n"
        "  /nav route Lorville to Port Tressler\n"
        "  /nav nodes stanton\n"
        "  /nav add-route GrimHEX \"Port Tressler\" 1.8 quantum\n"
        "  /nav add-jump Stanton-Pyro stanton pyro \"Aaron Halo\" \"Pyro Gateway\" L\n\n"
        "Aliases : /navigation /n /qt /quantum\n"
        "Les modifications ne sont pas sauvegardées automatiquement — pensez à /nav save.\n\n"
        "/nav populate\n"
        "  Interroge l'API UEX pour toutes les commodités achetables et importe\n"
        "  automatiquement les distances entre terminaux dans le graphe.\n"
        "  ~60 requêtes, couvre la majorité des terminaux actifs.\n"
        "  Aliases : /nav peupler  /nav enrichir  /nav remplir"
    ),
    "nav route": (
        "/nav route <départ> <arrivée>\n\n"
        "  Calcule le plus court chemin QT entre deux points du réseau.\n"
        "  Retourne la séquence de sauts, distances (Gm) et temps estimé.\n\n"
        "  <départ> et <arrivée> acceptent :\n"
        "    - Noms de terminaux, stations, villes (underscore ou espace)\n"
        "    - @local   Position courante du joueur\n"
        "    - @dest    Destination courante du joueur\n"
        "    - Préfixes : 'grim' → GrimHEX,  'area' → Area 18\n\n"
        "  Entre les deux noms, le mot 'to' ou 'vers' est optionnel.\n\n"
        "  Exemples :\n"
        "    /nav route GrimHEX Area18\n"
        "    /nav route Lorville to Port_Tressler\n"
        "    /nav route @local @dest\n"
        "    /nav route lorville new_babbage\n\n"
        "  Si la route passe par des jump points, ils sont indiqués.\n"
        "  Alias : /route from <a> to <b>"
    ),
    "dest": (
        "/dest                   Afficher la destination courante\n"
        "/dest <lieu>            Définir la destination (Tab pour compléter)\n"
        "/dest clear             Effacer la destination\n"
        "/dest effacer           Alias de clear\n\n"
        "Aliases : /d\n"
        "Pour effacer les deux (position + destination) : /go clear"
    ),
    "=": (
        "= <expression>               Calculer une expression arithmétique\n\n"
        "Opérateurs :\n"
        "  +  -  *  /    addition, soustraction, multiplication, division\n"
        "  x  X          alias de *  (ex: 16x6 = 96)\n"
        "  //            division entière  (ex: 17//3 = 5)\n"
        "  %             modulo / reste  (ex: 17%3 = 2)\n"
        "  ( )           parenthèses\n\n"
        "Décimales : point ou virgule  (ex: 1,5 * 4 = 6)\n\n"
        "Exemples :\n"
        "  = 16x6              → 96\n"
        "  = 100 / 3           → 33.3333\n"
        "  = (12 + 8) * 5      → 100\n"
        "  = 46 * 450 - 12000  → 8 700\n"
        "  = 1234 % 7          → 2\n\n"
        "Alias : /calc  /calculette  /calcul\n"
        "Le / est optionnel — '= 16x6' fonctionne sans /."
    ),
    "history": (
        "/history [n]             Afficher les n dernières commandes (défaut 50)\n"
        "/history stats           Statistiques (total, uniques, taille fichier)\n"
        "/history clear           Effacer l'historique\n\n"
        "Alias : /hist\n"
        "Exemple : /history 20  — affiche les 20 dernières commandes"
    ),
    "debug": (
        "/debug                   Afficher le niveau de trace actuel\n"
        "/debug <0-5>             Définir le niveau (0 = off, 5 = traces maximales)\n\n"
        "Niveaux :\n"
        "  0   Désactivé\n"
        "  1   Traces principales (normalize, parse, dispatch)\n"
        "  2   + informations complémentaires\n"
        "  3   + liste des commandes connues\n"
        "  4   + détails internes\n"
        "  5   Traces maximales"
    ),
    "dev": (
        "/dev                            Statut du mode dev et de la DB\n"
        "/dev on|off                     Activer/désactiver le mode dev (persisté)\n"
        "/dev scan import <dossier>      Importer tous les screenshots d'un dossier\n"
        "/dev scan import <dossier> all  Réimporter même les fichiers déjà traités\n"
        "/dev scan clear                 Vider la screenshot_db\n"
        "/dev db                         Statistiques et contenu de la screenshot_db\n"
        "/dev db list [n]                Lister les n dernières entrées (défaut 20)\n"
        "/dev calc.missions              Matrice missions : départ × destination × distance"
    ),
    "route": (
        "/route                           Routes depuis position courante\n"
        "/route from <terminal>           Routes depuis un terminal\n"
        "/route to <terminal>             Routes vers une destination\n"
        "/route --commodity <nom>         Filtrer sur une commodité\n"
        "/route --min-profit <aUEC>       Profit minimum\n"
        "/route --scu <n>                 Taille cargo"
    ),
    "mission": (
        "Deux magasins de données distincts — à ne pas confondre :\n"
        "  screenshot_db  BD des OCR brute pour préparer les traitenemnts d'importation\n"
        "                 * Alimentée par l'import automatique ou /dev scan import\n"
        "                 * Consultée par /mission scan\n"
        "  catalogue      Missions sélectionnées et validées par le joueur, permettant de lister la volonté première du parcours\n"
        "                 * Alimentée en sélectionnant dans /mission scan\n"
        "                 * Consultée par /mission list\n\n"
        "Workflow complet :\n"
        "  1. Prendre des screenshots (Impr Ecran) des contrats dans SC\n"
        "  2. /mission scan  →  affiche les missions OCR'd de la screenshot_db\n"
        "  3. Saisir une sélection (ex: all, 1,3,5-8)  →  ajout au catalogue\n"
        "  4. /mission list  →  voir et gérer le catalogue\n\n"
        "Commandes :\n"
        "/mission list                  Catalogue validé (étape 4)\n"
        "=== Gestion des scans de missions =================================\n"
        "/mission scan                  OCR récents → sélection (étape 2-3)\n"
        "/mission scan all              Toute la screenshot_db (toutes dates)\n"
        "/mission scan today            Captures depuis minuit\n"
        "/mission scan terminal         Terminaux scannés dans la base\n"
        "=== Gestion des missions en cours (catalogue) =====================\n"
        "/mission add                   Depuis le dernier /scan\n"
        "/mission add <fichier.jpg>     Scanner un screenshot directement\n"
        "/mission add <nom> ...         Saisie manuelle avec mots-clés\n"
        "/mission edit <id> ...         Modifier une mission du catalogue\n"
        "/mission remove <id>           Supprimer du catalogue\n\n"
        "Alias : /m\n\n"
        "Catégories OCR : hauling stellaire/interstellaire · récupération\n"
        "  chasse aux primes · mercenaire · collecte · enquête · livraison · minage · PvP\n\n"
        "/help mission scan   → détail du scan et de la sélection\n"
        "/help mission list   → détail de l'affichage catalogue\n"
        "/help mission add    → syntaxe complète de l'ajout manuel\n\n"
        "Icônes dans /mission list :\n"
        "  ⏱  objectif avec délai (TDD, shop, delay)\n"
        "  ⊙  même départ que d'autres missions du voyage\n"
        "  ⊕  même arrivée  ·  ⇄  mission relais"
    ),
    "mission scan": (
        "/mission scan [scope]\n\n"
        "  Consulte la screenshot_db (résultats OCR bruts) et propose une sélection.\n"
        "  !! Ces missions ne sont PAS encore dans le catalogue !!\n"
        "  Il faut les sélectionner ici pour qu'elles apparaissent dans /mission list.\n\n"
        "  Source : ~/.uexinfo/screenshot_db.json\n"
        "  Alimentée par : auto_ocr (watcher) ou /dev scan import <dossier>\n\n"
        "  Scopes :\n"
        "    (rien)    Fenêtre configurable (défaut : 2h) → /config scan hour <n>\n"
        "    all       Toute la base, toutes dates confondues\n"
        "    today     Captures depuis minuit\n"
        "    terminal  Terminaux scannés (pas les missions)\n\n"
        "  En CLI pur :\n"
        "    1. Tableau numéroté affiché\n"
        "    2. Saisir la sélection  (ex: 1,3,5-8  ou  all  ou  Entrée pour annuler)\n"
        "    3. Choisir la destination : c (catalogue seul)  ou  v (catalogue + voyage)\n"
        "    → Les missions sélectionnées apparaissent dans /mission list\n\n"
        "  En overlay : cases à cocher par session + boutons Ajouter/Voyage.\n\n"
        "  Déduplication : chaque fichier source est une clé unique.\n"
        "  Si SC affiche une animation entre deux captures de la même mission,\n"
        "  plusieurs lignes apparaissent — sélectionner la dernière.\n\n"
        "  Sessions : gap > session_gap min = nouvelle session.\n"
        "  Configurable : /config scan session_gap <min>  (défaut : 60)\n\n"
        "  Exemples :\n"
        "    /mission scan          Missions des 2 dernières heures\n"
        "    /mission scan all      Toute la base\n"
        "    /mission scan today    Aujourd'hui seulement"
    ),
    "mission add": (
        "/mission add\n"
        "  Depuis le dernier scan OCR (faire /scan ou /scan ecran avant)\n\n"
        "/mission add <fichier.jpg>\n"
        "  Scanne directement un screenshot de contrat de livraison\n\n"
        "/mission add <nom> reward:<aUEC>\n"
        "    [obj:<commodité> from:<source> to:<dest> scu:<n> [tdd|shop|delay:<r>]]+\n\n"
        "  Paramètres :\n"
        "    <nom>           Nom libre de la mission (avant le premier ':')\n"
        "    reward:<n>      Récompense en aUEC  (ex: reward:50000 ou reward:50k)\n"
        "    obj:<commod>    Nom de la commodité à livrer (démarre un objectif)\n"
        "    from:<lieu>     Terminal ou station de collecte\n"
        "    to:<dest>       Terminal ou station de livraison\n"
        "    scu:<n>         Quantité en SCU\n"
        "    tdd             Objectif nécessite le Terminal de Distribution\n"
        "    shop            Objectif nécessite un achat en boutique\n"
        "    delay:<raison>  Délai libre (ex: delay:48h)\n"
        "    note:<texte>    Note libre sur l'objectif\n\n"
        "  Plusieurs objectifs dans la même mission : répéter obj: ... :\n\n"
        "  Exemples :\n"
        "    /mission add \"Livraison Quant\" reward:50000 \\\n"
        "        obj:Quantainium from:HUR-L2 to:GrimHEX scu:12 tdd\n\n"
        "    /mission add Parcours reward:120k \\\n"
        "        obj:Laranite from:ARC-L1 to:Port_Tressler scu:8 \\\n"
        "        obj:Agricium from:Lorville to:Area18 scu:4\n\n"
        "    /mission add Mission_simple reward:30000 \\\n"
        "        obj:Copper from:Daymar to:GrimHEX scu:16"
    ),
    "mission edit": (
        "/mission edit <id> [clés...]\n\n"
        "  Modifie une mission existante. <id> = numéro ou nom de mission.\n\n"
        "  Clés disponibles :\n"
        "    name:<nom>      Renommer la mission\n"
        "    reward:<aUEC>   Modifier la récompense\n"
        "    obj:<commod>    Ajouter un objectif (même syntaxe que add)\n"
        "    from:<lieu>     Source du dernier obj: en cours\n"
        "    to:<dest>       Destination du dernier obj:\n"
        "    scu:<n>         Quantité SCU du dernier obj:\n"
        "    tdd / shop      Contrainte de délai sur le dernier obj:\n"
        "    delay:<raison>  Délai libre sur le dernier obj:\n\n"
        "  Note : edit ajoute les nouveaux objectifs aux existants.\n"
        "  Pour remplacer complètement, supprimer et recréer la mission.\n\n"
        "  Exemples :\n"
        "    /mission edit 3 reward:75000\n"
        "    /mission edit 3 name:\"Nouveau nom\"\n"
        "    /mission edit 3 obj:Agricium from:Lorville to:GrimHEX scu:8"
    ),
    "mission remove": (
        "/mission remove <id>\n\n"
        "  Supprime une mission du catalogue.\n"
        "  <id> = numéro affiché dans /mission list ou nom partiel.\n\n"
        "  Exemples :\n"
        "    /mission remove 3\n"
        "    /mission remove \"Livraison Quant\""
    ),
    "mission list": (
        "/mission list\n\n"
        "  Affiche le catalogue des missions validées.\n"
        "  !! Ne montre PAS les résultats OCR bruts de la screenshot_db !!\n"
        "  Pour voir les screenshots OCR'd → /mission scan\n"
        "  Pour y ajouter des missions → /mission scan → sélectionner → c ou v\n\n"
        "  Colonnes : # · Date scan · Nom · Départ → Arrivée · SCU · Récompense · Syn\n"
        "  Date scan : date/heure d'ajout au catalogue (pas la date du screenshot)\n\n"
        "  Icône ⏱ : objectif avec délai (TDD, shop, delay)\n"
        "  Syn : synergies entre missions du même voyage\n"
        "    ⊙ même départ  ⊕ même arrivée  ⇄ mission relais\n\n"
        "  Puis utilisez /voyage pour regrouper et planifier les missions."
    ),
    "voyage": (
        "/voyage                  Afficher le voyage actif (ou la liste)\n"
        "/voyage on               Activer le dernier voyage ou en créer un\n"
        "/voyage off              Désactiver (voyage conservé)\n"
        "/voyage new [nom]        Créer un nouveau voyage et l'activer\n"
        "/voyage list             Missions du voyage actif\n"
        "/voyage list --trajets   Liste de tous les voyages\n"
        "/voyage add [m1 m2 ...]  Ajouter des missions au voyage actif\n"
        "/voyage remove <m>       Retirer une mission\n"
        "/voyage clear            Vider toutes les missions du voyage\n"
        "/voyage name <nom>       Renommer le voyage actif\n"
        "/voyage copy [n|nom]     Copier/fusionner vers un autre voyage\n"
        "/voyage accept           Valider + analyser, désactiver le voyage\n"
        "/voyage later            Sauvegarder sans analyser, désactiver\n"
        "/voyage cancel           Annuler les modifications\n\n"
        "Adressage d'un voyage précis :\n"
        "  /voyage 2 list         Par numéro\n"
        "  /voyage -n2 list       Flag -n\n"
        "  /voyage MonVoyage add  Par nom\n\n"
        "Alias : /v\n"
        "/help voyage add     → ajouter des missions en détail\n"
        "/help voyage new     → créer et nommer un voyage\n"
        "/help voyage accept  → valider et analyser un voyage"
    ),
    "voyage new": (
        "/voyage new [nom]\n\n"
        "  Crée un nouveau voyage et l'active immédiatement.\n"
        "  Si aucun nom n'est fourni, un nom automatique est généré.\n"
        "  Le départ est initialisé à la position courante du joueur.\n\n"
        "  Exemples :\n"
        "    /voyage new\n"
        "    /voyage new \"Tournée Hurston\"\n"
        "    /voyage new Mission_du_jour\n\n"
        "  Après création, ajoutez des missions avec /voyage add."
    ),
    "voyage add": (
        "/voyage add [m1 m2 ...]\n\n"
        "  Ajoute une ou plusieurs missions au voyage actif.\n"
        "  <m> = identifiant (#) ou nom de mission affiché dans /mission list.\n\n"
        "  Sans argument : affiche le catalogue avec les missions déjà incluses.\n\n"
        "  Exemples :\n"
        "    /voyage add 1\n"
        "    /voyage add 1 2 3\n"
        "    /voyage add \"Livraison Quant\"\n\n"
        "  Pour adresser un voyage précis :\n"
        "    /voyage 2 add 1 3    → ajouter au voyage #2\n"
        "    /voyage -n2 add 1    → même chose avec flag -n\n\n"
        "  Si aucun voyage n'est actif : /voyage on  ou  /voyage new"
    ),
    "voyage remove": (
        "/voyage remove <m>\n\n"
        "  Retire une ou plusieurs missions du voyage actif.\n"
        "  <m> = identifiant ou nom de mission.\n\n"
        "  Exemples :\n"
        "    /voyage remove 2\n"
        "    /voyage remove 2 5"
    ),
    "voyage accept": (
        "/voyage accept\n\n"
        "  Valide le voyage actif :\n"
        "    1. Affiche le détail des missions\n"
        "    2. Analyse le voyage (lieux, SCU total, récompense, vaisseau suggéré)\n"
        "    3. Désactive le voyage (conservé dans la liste)\n\n"
        "  Utilisez /voyage accept quand vous avez terminé de planifier\n"
        "  et êtes prêt à exécuter les missions.\n\n"
        "  /voyage later  → sauvegarder sans analyser (pour reprendre plus tard)\n"
        "  /voyage off    → désactiver sans rien changer"
    ),
    "voyage on": (
        "/voyage on [n|nom]\n\n"
        "  Active un voyage existant ou en crée un nouveau automatiquement.\n\n"
        "  Sans argument : active le dernier voyage utilisé, ou crée un nouveau voyage\n"
        "  Avec un numéro ou un nom : active ce voyage précis.\n\n"
        "  Exemples :\n"
        "    /voyage on            → activer le dernier voyage (ou nouveau)\n"
        "    /voyage on 2          → activer le voyage #2\n"
        "    /voyage on Tournée    → activer le voyage nommé 'Tournée'\n\n"
        "  /voyage new [nom]  → créer un voyage avec un nom précis\n"
        "  /voyage off        → désactiver le voyage actif"
    ),
    "voyage off": (
        "/voyage off\n\n"
        "  Désactive le voyage actif sans le modifier.\n"
        "  Le voyage est conservé dans la liste et peut être repris à tout moment.\n\n"
        "  /voyage on        → réactiver le dernier voyage\n"
        "  /voyage later     → même effet (alias sémantique : 'pour plus tard')\n"
        "  /voyage accept    → valider + analyser avant de désactiver"
    ),
    "voyage name": (
        "/voyage name <nouveau_nom>\n\n"
        "  Renomme le voyage actif (ou un voyage ciblé avec -n).\n\n"
        "  Exemples :\n"
        "    /voyage name Tournée Hurston\n"
        "    /voyage name Mission_du_soir\n"
        "    /voyage 3 name Livraisons Microtech\n\n"
        "  Le nouveau nom peut contenir des espaces (pas de guillemets nécessaires).\n"
        "  Les underscores sont convertis en espaces."
    ),
    "voyage clear": (
        "/voyage clear\n\n"
        "  Retire toutes les missions du voyage actif.\n"
        "  Le voyage lui-même est conservé (nom, départ, arrivée).\n\n"
        "  /voyage delete    → supprimer entièrement le voyage\n"
        "  /voyage remove <m>  → retirer une seule mission"
    ),
    "voyage delete": (
        "/voyage delete [n… | --all]\n\n"
        "  Supprime un ou plusieurs voyages définitivement.\n\n"
        "  Sans argument : ouvre un sélecteur interactif\n"
        "  Avec numéros : supprime les voyages correspondants\n"
        "  --all : supprime tous les voyages (confirmation demandée)\n\n"
        "  Exemples :\n"
        "    /voyage delete          → sélecteur interactif\n"
        "    /voyage delete 2        → supprimer le voyage #2\n"
        "    /voyage delete 1 3 5    → supprimer les voyages #1, #3 et #5\n"
        "    /voyage delete --all    → tout supprimer\n\n"
        "  /voyage clear  → vider les missions sans supprimer le voyage"
    ),
    "voyage copy": (
        "/voyage copy [n|nom]\n\n"
        "  Copie les missions du voyage actif vers un autre voyage.\n"
        "  Si la destination n'existe pas, un nouveau voyage est créé.\n\n"
        "  Sans argument : copie vers un nouveau voyage (nom automatique)\n"
        "  Avec numéro ou nom : fusionne dans le voyage cible\n\n"
        "  Exemples :\n"
        "    /voyage copy              → nouveau voyage avec les mêmes missions\n"
        "    /voyage copy 2            → fusionner dans le voyage #2\n"
        "    /voyage copy Tournée      → fusionner dans le voyage 'Tournée'"
    ),
    "voyage later": (
        "/voyage later\n\n"
        "  Sauvegarde le voyage actif et le désactive sans l'analyser.\n"
        "  Utilisez cette commande quand vous voulez interrompre la planification\n"
        "  pour y revenir plus tard.\n\n"
        "  Le voyage est conservé dans la liste et peut être repris avec /voyage on.\n\n"
        "  /voyage accept  → valider + analyser avant de désactiver\n"
        "  /voyage off     → désactiver sans sauvegarder les modifications récentes"
    ),
    "voyage cancel": (
        "/voyage cancel\n\n"
        "  Annule toutes les modifications non sauvegardées du voyage actif.\n"
        "  Recharge l'état depuis le dernier enregistrement sur disque.\n\n"
        "  Utile si vous avez ajouté ou retiré des missions par erreur\n"
        "  et voulez revenir à l'état précédent.\n\n"
        "  /voyage later   → sauvegarder l'état actuel et désactiver\n"
        "  /voyage accept  → valider et analyser"
    ),
    "voyage calc": (
        "/voyage calc <critère> [options]\n\n"
        "  Génère automatiquement un voyage optimisé depuis les missions du catalogue.\n\n"
        "  Critères :\n"
        "    dist      Minimise la distance totale du voyage\n"
        "    benef     Maximise la récompense totale (aUEC)\n"
        "    roi       Maximise le retour sur investissement (aUEC/Gm)\n"
        "    all       Génère les 3 propositions simultanément\n\n"
        "  Options :\n"
        "    --max:N            Nombre max de missions par voyage\n"
        "    --boucle / --blc   Inclure le retour au départ\n"
        "    --station          Stations spatiales uniquement\n"
        "    --ship:nom         Filtrer par capacité SCU du vaisseau\n"
        "    --to <lieu>        Passer obligatoirement par ce lieu\n"
        "    --exclude <lieu>   Exclure ce lieu\n\n"
        "  Exemples :\n"
        "    /voyage calc roi --boucle --station\n"
        "    /voyage calc all --ship:Cutlass_Black\n"
        "    /voyage calc benef --to ArcCorp --exclude microTech\n\n"
        "  Après affichage des propositions :\n"
        "    +N     Ajouter la proposition N au voyage actif\n"
        "    +nN    Créer un nouveau voyage avec la proposition N\n"
        "    +mID   Ajouter uniquement la mission #ID au voyage actif\n\n"
        "  Config : /config voyage.calc.nbsaut  /config voyage.calc.options\n"
        "  Aide complète : /voyage calc help"
    ),
    "dev": (
        "/dev                            Statut mode dev + stats screenshot_db\n"
        "/dev on | off                   Activer/désactiver (persisté dans config)\n"
        "/dev scan import <dossier>      Import batch : OCR tous les .jpg/.png du dossier\n"
        "/dev scan import <dossier> all  Idem + force la réimportation des déjà traités\n"
        "/dev scan clear                 Supprimer screenshot_db.json (repart de zéro)\n"
        "/dev db                         Statistiques par type + plage temporelle\n"
        "/dev db list [n]                Dernières n entrées (défaut 20)\n\n"
        "Politique de skip par défaut (sans 'all') :\n"
        "  Ignorés  : type mission, terminal_buy, terminal_sell, terminal\n"
        "  Retentés : type unknown ou pending (OCR ayant échoué)\n"
        "  Nouveaux : absents de la DB\n\n"
        "Cas d'usage typique — importer des screenshots historiques :\n"
        "  /dev scan import extprg/SC-images\n"
        "  → Terminé — 105 mission(s)  33 terminal(s)  0 ignoré(s)  0 non reconnu(s)\n"
        "  /mission scan all\n"
        "  → tableau des 105 missions → saisir 'all' → ajout au catalogue\n\n"
        "Note : screenshot_db et catalogue sont deux stores séparés.\n"
        "  /dev scan import  peuple la screenshot_db\n"
        "  /mission scan     lit la screenshot_db et permet d'alimenter le catalogue\n"
        "  /mission list     affiche le catalogue (missions validées)"
    ),
    "voyage list": (
        "/voyage list              Missions du voyage actif (détail)\n"
        "/voyage list --trajets    Tous les voyages (vue synthèse)\n"
        "/voyage                   Identique à /voyage list\n\n"
        "  Vue synthèse (--trajets) : #, nom, missions, SCU, récompense, départ→arrivée\n"
        "  Vue détail : liste des missions avec départ, arrivée, distance, SCU, tags\n\n"
        "  Tags de synergies dans la vue détail :\n"
        "    ⊙  même départ qu'une autre mission du voyage\n"
        "    ⊕  même arrivée qu'une autre mission\n"
        "    ⇄  mission relais (dest d'une = source d'une autre)\n"
        "  ⏱  objectif avec contrainte de temps (TDD, shop, delay)"
    ),
    "voyage tb": (
        "/voyage tb [départ] [-N]\n\n"
        "  Tableau de bord : missions du voyage actif groupées par destination,\n"
        "  depuis le point de départ de l'étape N (défaut : étape 1).\n\n"
        "  Arguments :\n"
        "    [départ]   Lieu de départ explicite (sinon inféré depuis l'étape)\n"
        "    -N         Numéro d'étape (ex : -2 pour l'étape 2)\n\n"
        "  Sous-commandes :\n"
        "    /voyage tb list [-N]      Liste les étapes ou les missions d'une étape\n"
        "    /voyage tb compact        Supprime les étapes vides et renumérote\n"
        "    /voyage tb graph          Vue arbre des étapes et destinations\n"
        "    /voyage tb graph --scu    Arbre avec totaux SCU\n"
        "    /voyage tb graph --benef  Arbre avec récompenses\n\n"
        "  Exemples :\n"
        "    /voyage tb                → tableau depuis l'étape 1\n"
        "    /voyage tb -2             → tableau depuis l'étape 2\n"
        "    /voyage tb Hurston -2     → étape 2 avec départ forcé à Hurston\n"
        "    /voyage tb list           → liste toutes les étapes\n"
        "    /voyage tb list -2        → missions de l'étape 2\n"
        "    /voyage tb graph          → vue arbre du voyage\n"
        "    /voyage tb compact        → nettoyer les étapes vides"
    ),
}


@register("help", "h", "?")
def cmd_help(args: list[str], ctx) -> None:
    if args:
        # Essayer d'abord "cmd sub" (ex: "mission add"), puis "cmd" seul
        topic = args[0].lstrip("/").lower()
        sub_topic = f"{topic} {args[1].lower()}" if len(args) >= 2 else ""
        if sub_topic and sub_topic in _DETAILS:
            section(f"Aide — /{sub_topic}")
            console.print(_DETAILS[sub_topic])
        elif topic in _DETAILS:
            section(f"Aide — /{topic}")
            console.print(_DETAILS[topic])
        elif topic in _COMMANDS:
            console.print(f"[{C.LABEL}]/{topic}[/{C.LABEL}]  {_COMMANDS[topic]}")
        else:
            console.print(f"[{C.WARNING}]Pas d'aide pour « {' '.join(args)} »[/{C.WARNING}]")
        return

    section("UEXInfo — Commandes")
    from rich.table import Table
    t = Table(show_header=False, box=None, padding=(0, 2))
    t.add_column(style=f"bold {C.UEX}", no_wrap=True)
    t.add_column(style=C.NEUTRAL)
    for cmd, desc in _COMMANDS.items():
        t.add_row(f"/{cmd}", desc)
    console.print(t)
    console.print(
        f"\n[{C.DIM}]Tab = autocomplétion  │  ↑↓ = historique  │  /help <cmd> = aide détaillée[/{C.DIM}]"
    )
